name: Build Executable

on:
  push:
    branches: [master]

jobs:
  create-executable:
    runs-on: ubuntu-latest
    env:
      svelte-dir: ./actor-interface

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Snel
        run: deno run --allow-run --allow-read https://raw.githubusercontent.com/ntrotner/Snel/main/install.ts
        
      - name: Generate dist with Snel
        run: snel build
        working-directory: ${{env.svelte-dir}}

      - name: Copy dist to Root
        run: mv dist ../
        working-directory: ${{env.svelte-dir}}

      - name: Bundle Project to One File
        run: deno bundle main.ts main.bundled.ts 

      - name: Compile main.bundled.ts 
        run: deno compile --allow-net --allow-read --allow-write --allow-env=publicAddress,privateKey,actorUrl,actorNetID,pairPricerUrl,pairPricerNetID,sleepSeconds,defaultPriority --output main --no-check main.bundled.ts
        
      - name: Zip Resources to One File
        run: zip -r trading-actor.zip main .env.example dist
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{${{github.run_number}}/20}}
          files: trading-actor.zip
