name: Build Executable

on:
  push:
    branches: [master]

jobs:
  create-executable:
    runs-on: ubuntu-latest
    env:
      svelte-dir: ./actor-interface

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Install Snel
        run: deno run --allow-run --allow-read https://raw.githubusercontent.com/ntrotner/Snel/main/install.ts
        
      - name: Generate dist with Snel
        run: snel build
        working-directory: ${{env.svelte-dir}}
        
      - name: Move dist to Root
        run: mv dist ../
        working-directory: ${{env.svelte-dir}}

      - name: Bundle Project to One File
        run: deno bundle main.ts main.bundled.ts 

      - name: Compile main.bundled.ts 
        run: deno compile --allow-net --allow-read --output trading-actor --no-check main.bundled.ts
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            trading-actor
            settings.ts
            dist
