name: Build Executable

on:
  push:
    branches: [master]

jobs:
  create-executable:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Bundle Project to One File
        run: deno bundle main.ts main.bundled.ts 

      - name: Compile main.bundled.ts
        run: deno compile --allow-net --allow-read --allow-write --allow-env=publicAddress,privateKey,tradingActorUrl,tradingActorNetID,tradingActorContractAddress,ERC20TokenAddressPrimary,ERC20TokenAddressSecondary,pairPricerUrl,pairPricerNetID,sleepSeconds,defaultPriority,HTTPPort --output main --no-check main.bundled.ts

      - name: Zip Resources to One File
        run: zip -r trading-actor.zip main .env.example
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{github.run_number}}'
          files: trading-actor.zip
