name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  bot-code-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Verify Formatting
        run: deno fmt --log-level info --config ./deno.conf.json
        
      - name: Run Formatting
        run: deno lint --log-level info --config ./deno.conf.json
        
      - name: Commit Code Formatting
        uses: EndBug/add-and-commit@v8
        with:
          message: 'Formatted and Linted Deno Project'